apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fluent-bit
    kubernetes.io/cluster-service: "true"
    role: adapter
  name: fluent-bit
  namespace: log-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fluent-bit
      role: adapter
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/scrape: "true"
      labels:
        app: fluent-bit
        kubernetes.io/cluster-service: "true"
        role: adapter
    spec:
      containers:
      - image: docker.io/mattalberts/fluent-bit:1.4.6-s3-ed27f80
        imagePullPolicy: Always
        name: fluent-bit
        ports:
        - containerPort: 2020
          name: metrics-0
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluent-bit/etc/
          name: fluent-bit
          readOnly: true
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: fluent-bit-v1
        name: fluent-bit
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: log-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: log-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fluentd
    role: adapter
    step: capture
  name: fluent-bit-v1
  namespace: log-system
data:
  filter-kubernetes.conf: |+
    [FILTER]
      Name                kubernetes
      Match               kubernetes.*
      Kube_URL            https://kubernetes.default.svc:443
      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix     kubernetes.var.log.containers.
      Merge_Log           On
      Merge_Log_Key       log
      Keep_Log            On
      Use_Journal         Off
      K8S-Logging.Parser  Off
      K8S-Logging.Exclude Off
      Labels              On
      Annotations         Off

  fluent-bit.conf: |+
    [SERVICE]
      Flush         1
      Log_Level     info
      Daemon        off
      Parsers_File  parsers.conf
      HTTP_Server   On
      HTTP_Listen   0.0.0.0
      HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-s3.conf

  input-kubernetes.conf: |+
    [INPUT]
      Name              tail
      Tag               kubernetes.*
      Path              /var/log/containers/*.log
      Parser            docker
      DB                /var/log/fluent-bit-buffers/kubernetes.db
      Mem_Buf_Limit     512MB
      Skip_Long_Lines   Off
      Docker_Mode       On
      Docker_Mode_Flush 8
      Refresh_Interval  1
      Rotate_Wait       10
      Buffer_Chunk_Size 32k

  output-s3.conf: |+
    [OUTPUT]
      Name             s3
      Match            kubernetes.*
      Bucket           affirm-stage-logs
      S3Prefix         fluent-bit
      Region           us-east-1
      Compress         gzip
      AutoCreateBucket false
      LogLevel         info
      TimeZone         UTC
      Retry_Limit      5

  parsers.conf: |+
    [PARSER]
      Name        docker
      Format      json
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L
      Time_Keep   On

    [PARSER]
      Name        json
      Format      json
      Time_Key    time
      Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
      Name        syslog
      Format      regex
      Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
      Time_Key    time
      Time_Format %b %d %H:%M:%S
